# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flight_search.proto
# Protobuf Python Version: 6.30.0-rc2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '-rc2',
    'flight_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66light_search.proto\"\xc2\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x17\n\x06gender\x18\x03 \x01(\x0e\x32\x07.Gender\x12!\n\x05\x65mail\x18\x04 \x03(\x0b\x32\x12.Person.EmailEntry\x12\x13\n\x04\x63\x61rs\x18\x05 \x03(\x0b\x32\x05.Cars\x12\x12\n\nis_student\x18\x06 \x01(\x08\x12\n\n\x02hi\x18\x07 \x01(\x0c\x1a,\n\nEmailEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\"\n\x04\x43\x61rs\x12\x0c\n\x04make\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05*6\n\x06Gender\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04MALE\x10\x01\x12\n\n\x06\x46\x45MALE\x10\x02\x12\t\n\x05OTHER\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flight_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON_EMAILENTRY']._loaded_options = None
  _globals['_PERSON_EMAILENTRY']._serialized_options = b'8\001'
  _globals['_GENDER']._serialized_start=256
  _globals['_GENDER']._serialized_end=310
  _globals['_PERSON']._serialized_start=24
  _globals['_PERSON']._serialized_end=218
  _globals['_PERSON_EMAILENTRY']._serialized_start=174
  _globals['_PERSON_EMAILENTRY']._serialized_end=218
  _globals['_CARS']._serialized_start=220
  _globals['_CARS']._serialized_end=254
# @@protoc_insertion_point(module_scope)
